
import pandas as pd
from google.cloud import storage
import datetime
import snowflake.connector as sf
import json
from google.cloud import secretmanager
import io
from alert_mail import send_email
import re
from snowflake.connector.pandas_tools import write_pandas as wp

""" 
Function status codes:
   -1 ==> error
    0  ==> triggered by folder or upload of file which is not part of target path
    1  ==> File not in control table
    2  ==> Both metadata and validations
    3  ==> Only metadata
    4  ==> Anonymous
"""

def setting_environment_variables(payload_path):
    """
    Definition:
        Dictionary contains environment variables of dev, tst, and prd. Picking the right credentials based on the bucket on which trigger is created
    Args:
        payload_path (string): payload messsage path generated by the storage bucket trigger
    Returns:
        env_variables (dictionary): Environment variables of a given environment
    """
    
    f = open('env_variables.json')
    env_variables = json.load(f)
    f.close()
    bucket_name = payload_path.split('/',1)[0]
    environment = bucket_name.split('-')[2]
    env_variables = env_variables[environment]

    return env_variables
    

def get_secret(project_id,secret_name):

    """Definition: 
        Function to get the secret keys from the secrets manager
    Args:
        project_id (int): Project id where specified secret is present
        secret_name (string): Secret Name
    Returns:
        secret_string (string): Value of the secret key
    """

    client = secretmanager.SecretManagerServiceClient()
    secret_name = secret_name
    project_id = project_id
    request = {"name": f"projects/{project_id}/secrets/{secret_name}/versions/latest"}
    response = client.access_secret_version(request)
    secret_string = response.payload.data.decode("UTF-8")
    return secret_string


def detect_delimiter(first_line_in_the_file):
    """
    Definition:
        Detects the most occuring delimiter in the string
    Args:
        first_line_in_the_file (string):  first line of the file that is received in the bucket
    Returns:
        keymax (string): most occuring delimiter i.e. , (or) | (or) \t
    """

    delimiter_count = dict()
    delimiter_count[','] = first_line_in_the_file.count(',')
    delimiter_count['|'] = first_line_in_the_file.count('|')
    delimiter_count['\t'] = first_line_in_the_file.count('\t')

    # Get the key which has the highest value in the dictionary
    keymax = max(zip(delimiter_count.values(), delimiter_count.keys()))[1]

    return keymax


def establish_connection_to_snowflake(env_variables):
    """
    Definition:
        Establishes connection to snowflake
    Args:
        env_variables (dictionary):  Environment variables of a given environment
    Returns:
        sf_conn (object): Snowflake connection object
    """

    sf_conn = sf.connect(
                    user = f"{env_variables['user']}",
                    password= get_secret(project_id=env_variables['project_id'],secret_name='snowflake_service_acct_pwd'),
                    account = f"{env_variables['account']}",
                    warehouse = f"{env_variables['warehouse']}",
                    database = f"{env_variables['database']}",
                    schema = f"{env_variables['schema']}"
                    )

    return sf_conn


def insert_metadata_into_snowflake(payload_path, env_variables):
    """
    Definition:
        Inserts the metadata into the snowflake internal table
    Args:
        payload_path (string): payload messsage path generated by the storage bucket trigger
        env_variables (dictionary):  Environment variables of a given environment
    Returns:
        status_code (int): status code of the function
    """

    print('<Inserting metadata of the file into Snowflake logging table>')
    
    # Establishing Snowflake Connection
    sf_conn = establish_connection_to_snowflake(env_variables)

    client = storage.Client()

    # Splitting up the bucket name and file path inside the bucket
    path_to_file = payload_path.rsplit('/',1)[0]
    bucket_name = path_to_file.split('/')[0]
    file_path_in_bucket = path_to_file.split('/', 1)[1]
    file_name = payload_path.rsplit('/', 2)[-2]
    
    database = env_variables['database']
    schema = env_variables['schema']
    meta_table = env_variables['meta_table']
    error_table = env_variables['error_table']
    

    # Connecting to the bucket and file and loading the file into a Python DataFrame and removing unnamed columns
    bucket = client.get_bucket(f'{bucket_name}')
    file_blob = bucket.get_blob(f'{file_path_in_bucket}')
    
    
    try:
        first_line_in_the_file = file_blob.download_as_string().decode().split('\n')[0]
        file_delimiter = detect_delimiter(first_line_in_the_file)
        df = pd.read_csv(f'gs://{bucket_name}/{file_path_in_bucket}', sep = file_delimiter, low_memory=False)
    except Exception as e:
        print('------------------------Exception------------------------')
        e = str(e)
        e = e.replace("'"," ")
        e = e.replace('"'," ")
        with sf_conn as db_conn_sf:
            validation = pd.DataFrame({'Parameter':['Exception'],'File_name':[file_name],'File_path':[path_to_file], 'Expected_Value': [None], 'Actual_Value': [None], 'Description': [e]})
            wp(conn = db_conn_sf, df = validation, table_name = database + '.' + schema + '.' + error_table, quote_identifiers = False)
        print(f'Function failed due to exception: {e}')
        print('---------------------------------------------------------')
        return -1
        
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

    # Size of a file in bytes
    file_size_in_bytes = file_blob.size

    # Check if the file is Empty
    is_empty = df.empty

    # Number of rows and columns
    rows = len(df.axes[0])
    cols = len(df.axes[1])
    
    # Query to log metadata into Snowflake table
    sf_query = f"""INSERT INTO {database}.{schema}.{meta_table} (FILE_PATH, NUMBER_OF_ROWS, NUMBER_OF_COLUMNS, SIZE_OF_THE_FILE, IS_EMPTY) values('{path_to_file}',{rows}, {cols}, {file_size_in_bytes}, {is_empty});"""
    sf_conn.cursor().execute(sf_query)
    
    return 1


def minimum_size_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations):
    """
    Definition:
        Validates if the received file size is more than minimum threshold size
    Args:
        target_table (dataframe): Row in control table corresponding to the received file
        file_blob (object): blob object of the received file
        file_name (string): Name of the file received
        path_to_file (string): Path of the file
    Returns:
        df_failed_validations (dataframe): Dataframe with failed validations
    """

    file_size_min_kb = target_table['file_size_min_kb'].values[0]
    if(file_blob.size < file_size_min_kb * 1024):
        validation = pd.DataFrame({'Parameter':['file_size_min_kb'],'File_name':[file_name],'File_path':[path_to_file],'Expected_Value': [file_size_min_kb], 'Actual_Value': [(file_blob.size/1024)], 'Description': ['The uploaded file fails the minimum size validation']})
        df_failed_validations = pd.concat([df_failed_validations,validation]).reset_index(drop = True)

    return df_failed_validations


def maximum_size_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations):
    """
    Definition:
        Validates if the received file size is less than maximum threshold size
    Args:
        target_table (dataframe): Row in control table corresponding to the received file
        file_blob (object): blob object of the received file
        file_name (string): Name of the file received
        path_to_file (string): Path of the file
    Returns:
        df_failed_validations (dataframe):Dataframe with failed validations
    """
    
    file_size_max_mb = target_table['file_size_max_mb'].values[0]
    if(file_blob.size > file_size_max_mb * 1024 * 1024):
        validation = pd.DataFrame({'Parameter':['file_size_max_kb'],'File_name':[file_name],'File_path':[path_to_file], 'Expected_Value': [file_size_max_mb], 'Actual_Value': [(file_blob.size)/(1024*1024)], 'Description': ['The uploaded file fails the maximum size validation']})
        df_failed_validations = pd.concat([df_failed_validations,validation]).reset_index(drop = True)

    return df_failed_validations


def file_format_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations):
    """
    Definition:
        Validates if the received file format is one among the expected file formats
    Args:
        target_table (dataframe): Row in control table corresponding to the received file
        file_blob (object): blob object of the received file
        file_name (string): Name of the file received
        path_to_file (string): Path of the file
    Returns:
        df_failed_validations (dataframe):Dataframe with failed validations
    """

    file_format = target_table['file_format'].values[0].split(',')
    if(file_name.split('.')[-1] not in file_format):
        validation = pd.DataFrame({'Parameter':['file_format'],'File_name':[file_name],'File_path':[path_to_file], 'Expected_Value': [file_format], 'Actual_Value': file_name.split('.')[-1], 'Description': ['The uploaded file fails the file format validation']})
        df_failed_validations = pd.concat([df_failed_validations,validation]).reset_index(drop = True)

    return df_failed_validations
 
def column_names_validation(target_table, file_blob, file_name, path_to_file, bucket_name, file_path_in_bucket, df_failed_validations):
    """
    Definition:
        Validates if the received file columns are same as expected columns    
    Args:
        target_table (dataframe): Row in control table corresponding to the received file
        file_blob (object): blob object of the received file
        file_name (string): Name of the file received
        path_to_file (string): Path of the file
    Returns:
        df_failed_validations (dataframe):Dataframe with failed validations
    """

    control_columns = target_table['expected_columns'].values[0]
    control_columns = str(control_columns)

    # control_columns returns nan if there are no values for expected columns in the control table
    if control_columns == 'nan':
        print("This file doesn't have any headers in the control table and not being checked for file validations")
        df_failed_validations = pd.DataFrame()
        return df_failed_validations
        
    delimiter = target_table['delimiter'].values[0]

    # Replacing tab with \t and splitting the column names based on \t and removing unnamed columns
    if(delimiter=='tab'):
        df = pd.read_csv(io.StringIO(control_columns),sep='\t')
        expected_columns = list(df.columns.values)
    else:
        df = pd.read_csv(io.StringIO(control_columns),sep=delimiter)
        df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
        expected_columns = list(df.columns.values)
    
    first_line_in_the_file = file_blob.download_as_string().decode().split('\n')[0]
    file_delimiter = detect_delimiter(first_line_in_the_file)


    df = pd.read_csv(f'gs://{bucket_name}/{file_path_in_bucket}', sep = file_delimiter, low_memory=False)
    df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
    file_column_names = list(df.columns.values)

    if(file_column_names != expected_columns):
        validation = pd.DataFrame({'Parameter':['column_names'],'File_name':[file_name],'File_path':[path_to_file],'Expected_Value': [expected_columns], 'Actual_Value': [file_column_names], 'Description': ['The uploaded file fails the Column names validation'] })
        df_failed_validations = pd.concat([df_failed_validations,validation]).reset_index(drop = True)

        # df cannot handle list of items. So, typecasting it to string to handle the list
        df_failed_validations['Expected_Value']=df_failed_validations['Expected_Value'].apply(str)
        df_failed_validations['Actual_Value']=df_failed_validations['Actual_Value'].apply(str)

    return df_failed_validations


def delimiter_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations):
    """
    Definition:
        Validates if the received file delimiter is matching with the expected delimiter or not    
    Args:
        target_table (dataframe): Row in control table corresponding to the received file
        file_blob (object): blob object of the received file
        file_name (string): Name of the file received
        path_to_file (string): Path of the file
    Returns:
        df_failed_validations (dataframe):Dataframe with failed validations
    """

    delimiter = target_table['delimiter'].values[0]
    first_line_in_the_file = file_blob.download_as_string().decode().split('\n')[0]
    file_delimiter = detect_delimiter(first_line_in_the_file)
    if(delimiter == 'tab'):
        delimiter = '\t'
    if(file_delimiter != delimiter):
        validation = pd.DataFrame({'Parameter':['delimiter'],'File_name':[file_name],'File_path':[path_to_file],'Expected_Value': [delimiter], 'Actual_Value': [file_delimiter], 'Description': ['The uploaded file fails the delimiter validation'] })
        df_failed_validations = pd.concat([df_failed_validations,validation]).reset_index(drop = True)

    return df_failed_validations

def is_check(payload_path, env_variables):

    """
    Definition:
        Checks if the file uploaded needs to undergo data validations or not
    Args:
        payload_path (string): payload messsage path generated by the storage bucket trigger
        env_variables (dictionary):  Environment variables of a given environment
    Returns:
        is_check_flag (int): status code of the function
        target_table (Datframe): Dataframe with deatils of the uploaded file as per the control table
        status_message (string): Status message of the function
    """

    # Splitting up the bucket name and file path inside the bucket
    path_to_file = payload_path.rsplit('/',1)[0]
    bucket_name = path_to_file.split('/')[0]
    file_path_in_bucket = path_to_file.split('/', 1)[1]
    file_name = payload_path.rsplit('/', 2)[-2]

    sf_conn = establish_connection_to_snowflake(env_variables)

    database = env_variables['database']
    schema = env_variables['schema']
    table = env_variables['error_table']

    # Loading the control table into a Dataframe
    control_table_df = pd.read_csv(f'{env_variables["control_table_path"]}')

    # If the uploaded file is full load get the get the corresponding row from the dataframe
    target_table = control_table_df[control_table_df['file_name'].str.upper()== file_name.upper()]
    
    # If the file is incremental check for incremental file name pattern and get the corresponding row from dataframe
    if target_table.empty:
        incremental_file_name  = file_name.rsplit(".",1)[0]

        # using regex to find the pattern for incremental files like stop_yyyy_mm_dd or UPS 05 May 2023
        if (re.search("\d{8}$", incremental_file_name) is not None):
            incremental_file_name = incremental_file_name[:-9]
        elif (re.search("\s\d{4}$",incremental_file_name) is not None):
            incremental_file_name = incremental_file_name.rsplit('-',1)[0]
        incremental_file_name = incremental_file_name.strip()
        # print("The incremental file name is ",incremental_file_name)
        target_table = control_table_df[control_table_df['file_name'].str.upper()== incremental_file_name.upper()]
        
    if target_table.empty:
        validation = pd.DataFrame({'Parameter':['file_missing'],'File_name':[file_name],'File_path':[path_to_file], 'Expected_Value': [None], 'Actual_Value': [None], 'Description': ['The uploaded file is not present in control table']})
        wp(conn = sf_conn, df = validation, table_name = database + '.' + schema + '.' + table, quote_identifiers = False)
        return -1, None, "File does not exist in control table"
    else:
        is_check_flag = target_table['is_check'].values[0]
        return is_check_flag, target_table, 'File exists in control table'
    

                
def data_validation(payload_path, env_variables, target_table):
    """
    Definition:
        Function calls all the data validation checks
    Args:
        payload_path (string): path generated by the trigger
        env_variables (dict): environment variables
        target_table (Datframe): Dataframe with deatils of the uploaded file as per the control table
    Returns:
        status_code (int): status code of the function
    """
    
    print('<Checking for data validations of the uploaded file>')

    # Declaring a Dataframe to capture all the failed data validation checks
    df_failed_validations = pd.DataFrame(columns = ['Parameter','File_name','File_path','Expected_Value', 'Actual_Value', 'Description'])
    client = storage.Client()

    # Splitting up the bucket name and file path inside the bucket
    path_to_file = payload_path.rsplit('/',1)[0]
    bucket_name = path_to_file.split('/')[0]
    file_path_in_bucket = path_to_file.split('/', 1)[1]
    file_name = payload_path.rsplit('/', 2)[-2]


    # Connecting to the bucket and file and loading the file into a Python DataFrame
    bucket = client.get_bucket(f'{bucket_name}')
    file_blob = bucket.get_blob(f'{file_path_in_bucket}')

    sf_conn = establish_connection_to_snowflake(env_variables)

    df_failed_validations = minimum_size_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations)
    df_failed_validations = maximum_size_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations)
    df_failed_validations = file_format_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations)
    df_failed_validations = delimiter_validation(target_table, file_blob, file_name, path_to_file, df_failed_validations)
    df_failed_validations = column_names_validation(target_table, file_blob, file_name, path_to_file, bucket_name, file_path_in_bucket, df_failed_validations)

    # Storing the results into a bucket and sending alert
    if(df_failed_validations.empty == False):
        database = env_variables['database']
        schema = env_variables['schema']
        table = env_variables['error_table']
        sf_conn = establish_connection_to_snowflake(env_variables)

        print('Uploaded file fails data validation checks. Inserting them into Snowflake')

        with sf_conn as db_conn_sf:
            wp(conn = db_conn_sf, df = df_failed_validations, table_name = database + '.' + schema + '.' + table, quote_identifiers = False)
    
    return 1
        

def ingested_file_validation(event, context):
    """
    Definition:
        Entry to the function. When files uploads to the bucket
    Args:
        event (dict): assosciated values of the file uploaded
        context (obj): contains metadata about the event
    Returns:
        Failed or success status
    """
    try:
        start = datetime.datetime.now()
        payload_path = event['id']
        env_variables = setting_environment_variables(payload_path)
        print(f'The file uploaded is : {payload_path}')
        
        # Log into snowflake only if the file gets uploaded into the target folder that we are concerned with. If the GCF is triggered by any other file apart from the target folder, exit from the function.
        valid_path = env_variables['base_path'] 
        substring_in_list = any(string.upper() in payload_path.upper() for string in valid_path)
        if substring_in_list == False:
            print('The file uploaded is not being checked as it is not part of target paths')
            return 0
        
        pay_load_split = payload_path.split('/')
        if ('' in pay_load_split):
            print('The function is triggered because of creation of a folder')
            return 0
            
        else:
            is_check_flag, target_table, check_function_status = is_check(payload_path, env_variables)
            print(check_function_status)
            
            if is_check_flag == 1:
                ans = insert_metadata_into_snowflake(payload_path,env_variables)
                if ans == -1:
                    return -1

                # Calling Data validation function
                data_validation(payload_path, env_variables, target_table)
                
                return 2
                
            elif is_check_flag == 0:
                ans = insert_metadata_into_snowflake(payload_path,env_variables)
                if ans == -1:
                    return -1
                
                return 3
                    
            else:
                return 1
        
        end = datetime.datetime.now()
        return 4

    except Exception as e:
        print('------------------------Exception------------------------')
        e = str(e)
        e = e.replace("'"," ")
        e = e.replace('"'," ")
        
        sf_conn = establish_connection_to_snowflake(env_variables)
        database = env_variables['database']
        schema = env_variables['schema']
        error_table = env_variables['error_table']
        
        path_to_file = payload_path.rsplit('/',1)[0]
        file_name = payload_path.rsplit('/', 2)[-2]
        
        with sf_conn as db_conn_sf:
            validation = pd.DataFrame({'Parameter':['Exception'],'File_name':[file_name],'File_path':[path_to_file], 'Expected_Value': [None], 'Actual_Value': [None], 'Description': [e]})
            wp(conn = db_conn_sf, df = validation, table_name = database + '.' + schema + '.' + error_table, quote_identifiers = False)
        print(f'Function terminated due to exception: {e}')
        print('---------------------------------------------------------')
        return -1